Fusion-main/FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fusion-main/FusionIIIT/applications/feeds/urls.py
from django.conf.urls import url

from . import views

app_name = 'feeds'

urlpatterns=[
	#feeds homepage,profile and feeds admin
	url(r'^$', views.feeds, name= 'feeds'),
	url(r'^profile/(?P<string>[-\w]+)/$', views.profile, name= 'profile'),
	url(r'^administrative/(?P<string>[-\w]+)/$', views.administrativeView, name= 'administrative_view'),
	url(r'^admin',views.admin, name='feeds_admin'),
	url(r'^request/$', views.Request, name= 'request'),
	#deleting and updating comments and answers
	url(r'^comment_text/$', views.Comment_Text, name='comment_text'),
	url(r'^reply_text/$', views.Reply_Text, name='reply_text'),
	url(r'^update_answer/$', views.update_answer, name='update_answer'),
	url(r'^update_comment/$', views.update_comment, name='update_comment'),
	url(r'^delete_comment/$', views.delete_comment, name='delete_comment'),
	url(r'^delete_answer/$', views.delete_answer, name='delete_answer'),
	url(r'^like_comment/$', views.LikeComment, name='like_comment'),
	#deleting, updating, hiding and unhiding a post
	url(r'^(?P<id>[0-9]+)/delete_post/$', views.delete_post, name='delete_post'),
	url(r'^(?P<id>[0-9]+)/update_post/$', views.update_post, name='update_post'),
	url(r'^(?P<id>[0-9]+)/hide_post/$', views.hide_post, name='hide_post'),
	url(r'^(?P<id>[0-9]+)/unhide_post/$', views.unhide_post, name='unhide_post'),
	#remove a tag from taglist
	url(r'^remove_tag/$', views.RemoveTag, name= 'remove_tag'),
	#going to a particular question 
	url(r'^question_id_/(?P<id>[0-9]+)/$', views.ParticularQuestion, name= 'single_question'),
	#upvoting and downvoting a question and answers
	url(r'^upvote_ques/(?P<id>[0-9]+)$', views.upvoteQuestion, name='upvote_ques'),
	url(r'^downvote_ques/(?P<id>[0-9]+)$', views.downvoteQuestion, name='upvote_ques'),
	url(r'^upvote_answer/(?P<id>[0-9]+)$', views.upvoteAnswer, name='upvote_answer'),
	url(r'^downvote_answer/(?P<id>[0-9]+)$', views.downvoteAnswer, name='upvote_answer'),
	#questions selected based on selected tags
	url(r'^(?P<string>[-\w]+)/$', views.TagsBasedView, name= 'tag_based_view'),
]

Fusion-main/FusionIIIT/applications/globals/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'globals'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^about/', views.about, name='about'),
    # generic profile endpoint, displays or redirects appropriately
    url(r'^profile/(?P<username>.+)/$', views.profile, name='profile'),
    # profile of currently logged user
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^search/$', views.search, name='search'),
    # Feedback and issues url
    url(r'^feedback/$', views.feedback, name="feedback"),
    url(r'^issue/$', views.issue, name="issue"),
    url(r'^view_issue/(?P<id>\d+)/$', views.view_issue, name="view_issue"),
    url(r'^support_issue/(?P<id>\d+)/$', views.support_issue, name="support_issue"),
    url(r'^logout/$', views.logout_view, name="logout_view"),
    # Endpoint to reset all passwords in DEV environment
    url(r'^resetallpass/$', views.reset_all_pass, name='resetallpass'),
    # API urls
    url(r'^api/', include('applications.globals.api.urls'))
]

Fusion-main/FusionIIIT/applications/feeds/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from markdown_deux import markdown

from applications.globals.models import ExtraInfo


class Constants:
	"""
	contains record of all tags and subtags
	'TAG_LIST' - record of all tags
	'SUBTAG_LIST' -  record of all subtags
	"""

	TAG_LIST = (
		('CSE', 'CSE'),
		('ECE', 'ECE'),
		('Mechanical', 'Mechanical'),
		('Technical-Clubs', 'Technical Clubs'),
		('Cultural-Clubs', 'Cultural Clubs'),
		('Sports-Clubs', 'Sports Clubs'),
		('Business-and-Career', 'Business and Career'),
		('Entertainment', 'Entertainment'),
		('IIITDMJ-Campus', 'IIITDMJ Campus'),
		('Jabalpur-city', 'Jabalpur city'),
		('IIITDMJ-Rules-and-Regulations', 'IIITDMJ rules and regulations'),
		('Academics', 'Academics'),
		('IIITDMJ', 'IIITDMJ'),
		('Life-Relationship-and-Self', 'Life Relationship and Self'),
		('Technology-and-Education', 'Technology and Education'),
		('Programmes', 'Programmes'),
		('Others', 'Others'),
		('Design', 'Design'),
	)

	SUBTAG_LIST = (
		('Web-Development', 'Web Development'),
		('Competitive-Programming', 'Competitive Programming'),
		('Programming-Languages', 'Programming-Languages'),
		('Data-Science', 'Data-Science'),
		('Ethical-Hacking-and-Cyber-Security', 'Ethical hacking and cyber security'),
		('Cryptography-and-Network-Security', 'cryptography and network security'),
		('Software-Engineering', 'Software-Engineering'),
		('Algorithm', 'Algorithm'),
		('Mobile-Development', 'Mobile-Development'),
		('Game-Development', 'Game-Development'),
		('Artificial-Intelligence', 'Artificial Intelligence'),

		('Electronics-Circuit-Design', 'Electronics Circuit Design'),
		('Wireless-Communication', 'Wireless Communication'),
		('Embedded-System', 'Embedded Systems'),
		('VLSI', 'VLSI'),
		('Control-System', 'Control Systems'),
		('Robotics-and-others', 'Robotics and Others'),
		('Microcontrollers', 'Microcontrollers'),
		('IOT', 'IOT'),

		('Robotics', 'Robotics'),
		('Thermodynamics', 'Thermodynamics'),
		('Nanatechnology', 'Nanatechnology'),
		('Manufacturing', 'Manufacturing'),

		('Programming-and-Webix-Club', 'Programming and Webix Club'),
		('Electronics-Club', 'Electronics Club'),
		('Business-and-Management-Club', 'Business and Management Club'),
		('Robotics-Club', 'Robotics Club'),
		('CAD-Club', 'CAD Club'),
		('Astronomy-and-Physics-Society', 'ASTRONOMY AND PHYSICS SOCIETY'),
		('Aakriti-The-Film-Making-and-Photography-Club', 'AAKRITI-THE FILM MAKING AND PHOTOGRAPHY CLUB'),
		('AUTOMOTIVE-AND-FABRICATION-CLUB', 'AUTOMOTIVE AND FABRICATION CLUB'),
		('RACING-CLUB', 'RACING CLUB'),

		('SAAZ-MUSIC-CLUB', 'SAAZ-MUSIC CLUB'),
		('SAMVAAD-THE-LITERATURE-AND-QUIZZING-SOCIETY', 'SAMVAAD-THE LITERATURE AND QUIZZING SOCIETY'),
		('ABHIVYAKTI-ARTS-CLUB', 'ABHIVYAKTI-ARTS CLUB'),
		('JAZBAAT-THE-DRAMATICS-SOCIETY', 'JAZBAAT-THE DRAMATICS SOCIETY'),
		('AAVARTAN-DANCE-CLUB', 'AAVARTAN-DANCE CLUB'),

		('BADMINTON-CLUB', 'BADMINTON CLUB'),
		('LAWN-TENNIS-&-BASKETBALL-CLUB', 'LAWN TENNIS&BASKETBALL CLUB'),
		('TABLE-TENNIS', 'TABLE TENNIS'),
		('CHESS-&-CARROM-CLUB', 'CHESS & CARROM CLUB'),
		('CRICKET-CLUB', 'CRICKET CLUB'),
		('FOOTBALL-CLUB', 'FOOTBALL CLUB'),
		('VOLLEYBALL-CLUB', 'VOLLEYBALL CLUB'),
		('ATHLETICS-CLUB', 'ATHLETICS CLUB'),

		('Business-Models-and-Strategies', 'Business Models and strategies'),
		('Startups-and-Stratup-Strategies', 'Startups and Stratup Strategies'),
		('Entrepreneurship', 'Entrepreneurship'),
		('Finance', 'Finance'),
		('Marketing', 'Marketing'),
		('Stock-Market', 'Stock market'),
		('Career-Advice', 'Career Advice'),
		('Job-Interviews', 'Job Interviews'),

		('Journalism', 'Journalism'),
		('Entertainment', 'Entertainment'),
		('Hollywood-and-Movies', 'Hollywood and Movies'),
		('Music', 'Music'),
		('Fashion-and-Style', 'Fashion and Style'),

		('IIITDMJ-Campus', 'IIITDMJ-Campus'),

		('Jabalpur-City', 'Jabalpur City'),

		('IIITDMJ-rules-and-Regulations', 'IIITDMJ rules and regulations'),

		('Academic-Office-Stuffs', 'Academic office stuffs'),
		('Academic-Courses', 'Academic courses'),

		('Central-Mess', 'Central Mess'),
		('Alumni', 'Alumni'),
		('Hostels', 'Hostels'),
		('PHC', 'PHC'),
		('Activities', 'Activities'),
		('Counselling', 'Counselling'),
		('Achievments', 'Achievments'),
		('Library', 'Library'),
		('Faculty', 'Faculty'),
		('Staff', 'Staff'),
		('College-Fest', 'College Fest'),
		('Workshops', 'Workshops'),
		('Campus-Recruitments', 'Campus Recruitments'),
		('Jagrati', 'Jagrati'),

		('Self-Improvement', 'Self Improvement'),
		('Friendship', 'Friendship'),
		('Experiences', 'Experiences'),
		('Dating-and-Relationships', 'Dating and Relationships'),
		('Interpersonal-Interactions', 'Interpersonal Interactions'),
		('Life-and-Social-Advice', 'Life and Social Advice'),
		('Philosophy', 'Philosophy'),

		('Technology-Trends', 'Technology Trends'),
		('TED', 'TED'),
		('Higher-Education', 'Higher Education'),
		('Science-and-Universe', 'Science and Universe'),
		('Social-Media', 'Social-Media'),
		('Toron', 'Toron'),
		('Jobs-and-Internships', 'Jobs and Internships'),

		('Btech', 'Btech'),
		('Mtech', 'Mtech'),
		('Bdes', 'Bdes'),
		('Mdes', 'Mdes'),
		('Phd', 'Phd'),
		('Mechatronics', 'Mechatronics'),

		('others', 'others'),

	)


# Create your models here.


class AllTags(models.Model):
	"""
	records tags and subtags in database
	"""
    # new = models.CharField(max_length=100, blank=True, null=True)
	tag = models.CharField(max_length=100, default='CSE', choices=Constants.TAG_LIST)
	subtag = models.CharField(max_length=100, unique=True, default='Web-Development', choices=Constants.SUBTAG_LIST)

	def __str__(self):
		return '{} - {}'.format(self.tag, self.subtag)

class AskaQuestion(models.Model):
	"""
	Records questions asked by users
	"""
	can_delete=models.BooleanField(default=False)
	can_update=models.BooleanField(default=False)
	user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
	subject = models.CharField(max_length=100, blank=False)
	description = models.CharField(max_length=500, null=True, blank=True, default="")
	select_tag = models.ManyToManyField(AllTags)
	file = models.FileField(null=True, blank=True,upload_to='feeds/files')
	uploaded_at = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)
	likes = models.ManyToManyField(User, default=1,related_name='likes', blank=True)
	dislikes = models.ManyToManyField(User, default=1,related_name='dislikes', blank=True)
	requests = models.ManyToManyField(User, default=1,related_name='requests', blank=True)
	is_liked=models.BooleanField(default=False)
	is_requested=models.BooleanField(default=False)
	request = models.IntegerField(default=0)
	anonymous_ask = models.BooleanField(default=False)
	total_likes=models.IntegerField(default=0)
	total_dislikes=models.IntegerField(default=0)

	# class Meta:
	# 	unique_together = ('subject', 'select_tag')

	def total_likes(self):
		return self.likes.count()

	def total_dislikes(self):
		return self.dislikes.count()

	def total_requests(self):
		return self.requests.count()

	def get_markdown(self):
		content = self.description
		markdown_text = markdown(content)
		markdown_text = mark_safe(markdown_text)
		return markdown_text

	def __str__(self):
		return '{} added ----> {} in {}'.format(self.user, self.subject, self.select_tag)

class AnsweraQuestion(models.Model):
	"""
	Records answers on a question
	"""
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	content = models.TextField(max_length=1000, blank=False)
	question = models.ForeignKey(AskaQuestion, default=1, on_delete=models.CASCADE)
	uploaded_at = models.DateTimeField(auto_now=False, auto_now_add=False, default=timezone.now)
	answers = models.ManyToManyField(User, default=1, related_name='answers', blank=True)
	total_answers = models.IntegerField(default=0)
	likes = models.ManyToManyField(User, default=1,related_name='answer_likes', blank=True)
	dislikes = models.ManyToManyField(User, default=1,related_name='answer_dislikes', blank=True)
	is_liked=models.BooleanField(default=False)

	def total_likes(self):
		return self.likes.count()

	def total_votes(self):
		return self.likes.count() - self.dislikes.count()

	def total_dislikes(self):
		return self.dislikes.count()

	def total_requests(self):
		return self.requests.count()

	def __str__(self):
		return '{} - answered the question - {}'.format(self.content, self.question)

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		markdown_text = mark_safe(markdown_text)
		return markdown_text

	def total_answers(self):
		return self.answers.count()

class Comments(models.Model):
	"""
	Records comments on posts
	"""
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	question = models.ForeignKey(AskaQuestion, default=1 , on_delete = models.CASCADE)
	comment_text = models.CharField(max_length=5000)
	likes_comment = models.ManyToManyField(User, default=1,related_name='likes_comment', blank=True)
	total_likes_comment = models.IntegerField(default=0)
	commented_at = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)
	is_liked = models.BooleanField(default=False)

	def __str__(self):
		return self.comment_text

	def total_likes_comment(self):
		return self.likes_comment.count()

class Reply(models.Model):
	"""
	Records replies on a post
	"""
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	comment = models.ForeignKey(Comments,default=1, on_delete=models.CASCADE)
	msg = models.CharField(max_length=1000)
	content = models.CharField(max_length=5000, default="")
	replies = models.ManyToManyField(User, default=1,related_name='replies', blank=True)
	total_replies = models.IntegerField(default=0)
	replied_at = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)

	def __str__(self):

Fusion-main/FusionIIIT/applications/feeds/forms.py
from django import forms
from pagedown.widgets import PagedownWidget

from .models import AnsweraQuestion, AskaQuestion, Comments, Profile


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comments
		fields = ('comment_text',)

class AnswerForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(attrs={"show_preview":False}))
	class Meta:
		model = AnsweraQuestion
		fields = [
			'content'
		]

class QuestionForm(forms.ModelForm):
	description = forms.CharField(widget=PagedownWidget(attrs={"show_preview":False}))
	class Meta:
		model = AskaQuestion
		fields = [
			'description',
		]

class ProfileForm(forms.ModelForm):
	profile_picture = forms.ImageField()
	bio = forms.CharField()
	class Meta:
		model = Profile
		fields = [
			'profile_picture',
			"bio"
		]

Fusion-main/FusionIIIT/templates/feeds/admin.html
{% extends 'globals/base.html' %}
{% load static %}


{% block title %}
    Feeds Admin
{% endblock %}

{% block css %}

 <link href="https://cdn.rawgit.com/mdehoog/Semantic-UI/6e6d051d47b598ebab05857545f242caf2b4b48c/dist/semantic.min.css" rel="stylesheet" type="text/css" />

{% endblock %}

{% block body %}
    {% block navBar %}
        {% include 'dashboard/navbar.html' %}
    {% endblock %}


    {% comment %}The grid starts here!{% endcomment %}
    <div class="ui stackable doubling grid">

        {% comment %}The left-margin segment!{% endcomment %}
        <div class="column"></div>

        <div class="three wide column">

            {% comment %}The user image card starts here!{% endcomment %}
            {% block usercard %}
                {% include 'globals/usercard.html' %}
            {% endblock %}
            {% comment %}The user image card ends here!{% endcomment %}

            <div class="ui divider"></div>

            {% comment %}The Tab-Menu starts here!{% endcomment %}
            {% comment %} <div class="ui huge fluid vertical pointing menu"
                 style="max-width: 320px;">

                <a class="item" href="{% url 'globals:profile' %}">
                    View Profile
                    <i class="right floated chevron right icon"></i>
                </a>

            </div> {% endcomment %}
            {% comment %}The Tab-Menu ends here!{% endcomment %}

        </div>

        <div class="eight wide column">
            {% if administrativeRole %}
                <div class="ui success message">
                    <h3 class="ui header"> You are assigned {{role_user}} role. You can start posting updates from right side panel.</h3>
                </div>
            {% else %}
                <div class="ui success message">
                    <h3 class="ui header"> You are not assigned to any role.</h3>
                </div>
            {% endif %}

            {% with isBreak=False %}
            {% for r in role %}
            {% if isBreak %}
            <!-- do nothing  -->
            {% elif r.role == 'FeedsAdmin' and r.user == request.user %}
                {% include 'feeds/admin_middle.html'%}

            {% with isBreak=True %}
            {% endwith %}

            {% endif %}

            {% endfor %}
            {% endwith %}



        </div>

        {% comment %}The right-rail segment starts here!{% endcomment %}
        <div class="three wide column">
            {% include 'feeds/third_section.html' %}
        </div>
        <div class="column"></div>

    </div>
    {% comment %}The grid ends here!{% endcomment %}



{% endblock %}

Fusion-main/FusionIIIT/templates/feeds/answer_display.html
{{ instance.get_markdown }}

Fusion-main/FusionIIIT/templates/feeds/reply_section.html
{% for reply in comment.reply_set.all|dictsortreversed:"replied_at" %}
	{{reply.content}}
	<p>-{{reply.user}}</p>
	<p>{{reply.replied_at}}</p>
	<br>
{% endfor %}

Fusion-main/FusionIIIT/templates/feeds/testing.html
<!DOCTYPE html>
<html>
	<head>
		<title>Hello It's Alpha</title>
	</head>
	<body>
		<h1>Hello there kjsndks ksdjn</h1>
	</body>
</html>

Fusion-main/FusionIIIT/templates/feeds/third_section.html
{% load static %}
<div>
    <div class="ui success message center aligned">
        {% comment %} <div class="ui vertical buttons"> {% endcomment %}
            <button class="ui inverted  red button" id="modal-script">
            {% ifequal request.path "/feeds/admin" %}
                {% if is_admin or administrative_role %}
                Post update
                {% else %}
                Ask a Question?
                {% endif %}
            {% else %}
                Ask a Question?
            {% endifequal %}
            </button>
            <h3 class="ui header" style="margin:5px 0px">More Options:</h3>
            <div class="ui left labeled button" tabindex="0">
                <a class="ui basic right pointing label" href={% url 'feeds:feeds' %}>
                    Feed Home
                </a>
                <div class="ui button">
                    <i class="newspaper  outline icon"></i>
                </div>
            </div>

            <div class="ui divider"></div>

            <div class="ui left labeled button" tabindex="0">
                <a class="ui basic right pointing label" href={% url 'feeds:feeds_admin' %}>
                    Admin Panel
                </a>
                <div class="ui button">
                    <i class="shield alternate icon"></i>
                </div>
            </div>

            <div class="ui divider"></div>

            <div class="ui left labeled button" tabindex="0">
                <a class="ui basic right pointing label" href={% url 'feeds:profile' request.user.username %}>
                    Show Activity
                </a>
                <div class="ui button">
                    <i class="clipboard check icon"></i>
                </div>
            </div>
        {% comment %} </div> {% endcomment %}
    </div>
    {% comment %} <div class="ui success message"> {% endcomment %}
        <div class="ui fluid center aligned input inline fields">
            <form method="get" action="{% url 'feeds:feeds' %}">
            <input type="search" name="keyword" placeholder="Search in feeds...">
            <button type="submit" name="search" value="search" class="ui search button">
            <i class="ui search icon"></i></button>
            </form>
        </div>

        <div class="ui divider"></div>
    {% comment %} </div> {% endcomment %}
    {% ifnotequal request.path "/feeds/admin" %}
    <div class="ui success message">
        Filters:
        {{ request.path }}
    </div>
    {% endifnotequal%}
    <div class="ui success message">
        <h3 class="ui header">Feeds by Administration:</h3>
        <div class="ui middle  aligned divided list"  style="max-height: 180px; overflow-y: scroll;">
            {% for r in role %}
            <div class="item">
                <img class="ui avatar image" src={% static 'admin-settings-male.png' %}>
                <div class="content">
                <a class="header" href={% url 'feeds:administrative_view' r.role %}>{{r.role}}</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>


<!-- Modal Starts here...... -->
<div class="ui modal" id="post_modal">
    <i class="close icon"></i>
    <div class="ui header"><i class="ui user icon"></i>{{ username }}</div>
    <div class="scrolling content">
        <div class="ui message">
            <div class="header">
                Check these things
            </div>
            <ul class="list">
                <li>Please try to add How, What, Why in subject.</li>
                <li>Be specific to your problem.</li>
            </ul>
        </div>

        <form method="post" action="{% url 'feeds:feeds' %}" onsubmit="return ques_validate()" enctype="multipart/form-data">{% csrf_token %}
            <div class="ui large form">
                <div class="field">
                    <label>Subject</label>
                    <input id="subject" type="text" name="subject" placeholder="Subject for your problem..." required>
                </div>

                <div class="field">
                    {{ form_answer }}
                </div>

                <div class="field">
                    <label>Add Tag</label>
                        <div class='ui multiple search selection dropdown seasons'>
                            <input class="ques_Add_tag" name="Add_Tag" id="Add_Tag" value="Add_Tag" type="hidden">
                            <i class="dropdown icon"></i>
                            <div class="default text"><i class="tags icon"></i>Select</div>
                            <div class="menu">
                                {% for allowed_subtag in subtags %}
                                <div class="item" data-value="{{ allowed_subtag.id }}">{{ allowed_subtag.subtag }}</div>
                                {% endfor %}
                            </div>

                        </div>
                </div>

                <div class="field">
                    <label>Upload File</label>
                    <input type="file" id="file" name="file" style="border-radius: 3px;">
                </div>

                <div class="ui hidden divider"></div>
                <div class="field">
                    <div class="ui black checkbox">
                        <input type="checkbox" id="anonymous" name="anonymous">
                        <label>Ask Anonymously</label>
                    </div>
                </div>
                {% ifequal request.path "/feeds/admin" %}
                    {% if is_admin or administrative_role %}
                        <input type="text" id="from_admin" name="from_admin" value="from_admin" hidden>
                        <div class="field">
                            <div class="ui black checkbox">
                                <input type="checkbox" id="RestrictVote" name="RestrictVote">
                                <label>Restrict Vote?</label>
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui black checkbox">
                                <input type="checkbox" id="RestrictAnswer" name="RestrictAnswer">
                                <label>Restrict Answer?</label>
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui black checkbox">
                                <input type="checkbox" id="RestrictComment" name="RestrictComment">
                                <label>Restrict Comment?</label>
                            </div>
                        </div>
                    {% endif %}
                {%endifequal%}
                <div class="ui hidden divider"></div>

                <div class="actions">
                    <button type="submit" name="add_qus" value="add_qus" class="ui submit positive button" style="float: right;">
                        Post
                    </button><br>
                    <div class="ui hidden divider"></div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Modal ends here -->


{% block javascript %}

    <script>
        function ques_validate(){
            var da = $(".ques_Add_tag").val();
            if(da == "Add_Tag")
                return false;
            else
                return true;
        }
    </script>

    <script>
        function update_ques_validate(id){
            var da = $(".update_Add_Tag"+id).val();
            console.log(da)
            if(da == "Add_Tag")
                return false;
            else
                return true;
        }
    </script>

    <!-- Modal for Ask a Question? -->
    <script type="text/javascript">
        $('#modal-script').on('click', function(){
            $('#post_modal')
            .modal('show');
        });

        $('#report').on('click', function(){
            $('#report_modal')
            .modal('show');
        });

        $(document).ready(function(){
            $(document).on("click","#update_post",function(){
                {% comment %} alert($(this).attr('value')); {% endcomment %}
                $('#update_modal'+ $(this).attr('value'))
                .modal('show');
            });

            $(document).on("click","#delete_post",function(){
                {% comment %} alert('#delete_post'+ $(this).attr('value')); {% endcomment %}
                $('#delete_modal'+ $(this).attr('value'))
                .modal('show');
            });

            $(document).on("click","#hide_post",function(){
                {% comment %} alert('#hide_post'+ $(this).attr('value')); {% endcomment %}
                $('#hide_modal'+ $(this).attr('value'))
                .modal('show');
            });
        });

        $('#answer').on('click', function(){
            console.log("give answer")
            $('#answer_modal')
            .modal('show');
        });
    </script>
    <!-- Modal ends here -->
    <script>
    if ( window.history.replaceState ) {
    window.history.replaceState( null, null, window.location.href );
    }
    </script>
{% endblock javascript %}