Fusion-main/FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fusion-main/FusionIIIT/applications/establishment/urls.py
from django.conf.urls import url
from . import views
from django.urls import include,path
app_name = 'establishment'

urlpatterns = [
    url(r'^$', views.establishment, name='establishment'),
    url(r'cpda/', views.cpda, name='cpda'),
    url(r'ltc/', views.ltc, name='ltc'),
    url(r'appraisal/', views.appraisal, name='appraisal')
]

Fusion-main/FusionIIIT/applications/establishment/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from applications.globals.models import ExtraInfo, HoldsDesignation, Designation
from applications.academic_information.models import Curriculum_Instructor
from applications.eis.models import (emp_consultancy_projects,emp_research_projects,
                                        emp_mtechphd_thesis,emp_patents,emp_techtransfer,
                                            emp_published_books,emp_confrence_organised,
                                            emp_achievement,emp_event_organized)
from django.db.models import Avg, Count, Min, Sum,Q
from datetime import datetime,date
from .models import *
from .forms import *
import numpy as np
from django.http import HttpResponse, HttpResponseRedirect
from dateutil.relativedelta import relativedelta

def initial_checks(request):
    return {}


def is_admin(request):
    """
        function to check if the user has designation "admin".
    """
    return request.user == Establishment_variables.objects.select_related('est_admin').first().est_admin


def is_eligible(request):
    return True


def is_hod(request):
    """
        function to check if the user has designation "HOD".
    """
    user_dsg = list(HoldsDesignation.objects.filter(user=request.user))
    if(len(user_dsg)==0):
        return False
    for i in range(len(user_dsg)):
        designation = user_dsg[i].designation.name
        if("HOD" in designation):
            return True
    return False


# def is_student(request):
    """
        function to check if the user has designation "student".
    """
    """ user_dsg = list(HoldsDesignation.objects.filter(user=request.user))
    if(len(user_dsg)==0):
        return False
    for i in range(len(user_dsg)):
        designation = user_dsg[i].designation.name
        if("student" in designation):
            return True
    return False """

def is_faculty(request):
    user = get_object_or_404(ExtraInfo, user=request.user)
    return user.user_type=='faculty'


def is_staff(request):
    user = get_object_or_404(ExtraInfo, user=request.user)
    return user.user_type=='staff'


def is_registrar(request):
    """
        function to check if the user has designation "Registrar".
    """
    user_dsg = list(HoldsDesignation.objects.filter(user=request.user))
    if(len(user_dsg)==0):
        return False
    desg = [des.designation.name for des in user_dsg]
    for d in desg:
        if("Registrar" in d):
            return True
    return False


def is_director(request):
    """
        function to check if the user has designation "Director".
    """
    user_dsg = list(HoldsDesignation.objects.filter(user=request.user))
    if(len(user_dsg)==0):
        return False
    desg = [des.designation.name for des in user_dsg]
    for d in desg:
        if("Director" in d):
            return True
    return False


def is_cpda(dictx):
    """
        function to check if the application is CPDA.
    """
    for key in dictx.keys():
        if 'cpda' in key:
            return True
    return False


def is_ltc(dictx):
    """
        function to check if the application is LTC.
    """
    for key in dictx.keys():
        if 'ltc' in key:
            return True
    return False


def is_appraisal(dictx):
    """
        function to check if the application is Appraisal.
    """
    for key in dictx.keys():
        if 'appraisal' in key:
            return True
    return False


def handle_cpda_admin(request):
    """
        Function handles the request of assigning/re-assigning reviewers of CPDA Application.
    """
    if 'cpda_assign_form' in request.POST:
        try:
            app_id = request.POST.get('app_id')
            remarks = request.POST.get('remarks')        
            application = Cpda_application.objects.select_related('applicant').get(id=app_id)
            application.tracking_info.current_reviewer_id+=1
            application.tracking_info.remarks_rev2 = remarks
            application.tracking_info.review_status = 'under_review'
            application.tracking_info.save()
            # notify
            messages.success(request, 'Applicaiton Verification successfull!')
        except Exception as e:
            messages.error(request,e)
    


def handle_ltc_admin(request):
    """
        Function handles the request of assigning/re-assigning reviewers of LTC Application.
    """
    
    if 'ltc_assign_form' in request.POST:
        try:
            app_id = request.POST.get('app_id')
            remarks = request.POST.get('remarks')
            # assign the app to the reviewer
            #finding Director
            designation = Designation.objects.filter(name = 'Director')
            holds_designation = HoldsDesignation.objects.filter(designation = designation[0])
            dir_desig=designation[0]
            director = holds_designation[0].user
            # print(designation)
            # print(holds_designation)
            # print(dir_desig)
            # print(director)
            # Getting reviewer designation
            application = Ltc_application.objects.select_related('applicant').get(id=app_id)
            application.tracking_info.reviewer_id = director
            application.tracking_info.reviewer_design = dir_desig
            application.tracking_info.admin_remarks = remarks
            application.tracking_info.review_status = 'under_review'
            application.tracking_info.save()
            application.save()
            # print("application",application)
            # print("application.tracking_info",application.tracking_info)
            # add notif
            messages.success(request, ' Review Submitted successfully!')
        except Exception as e:
            messages.error(request,e)

    # elif app_id:
    #     # update the status of app
    #     # verify that app_id is not changed, ie untampered
    #     application = Ltc_application.objects.select_related('applicant').get(id=app_id)
    #     application.status = status
    #     application.tracking_info.admin_remarks = remarks
    #     eligible_ltc_user=Ltc_eligible_user.objects.get(user=application.applicant)
    #     if(application.is_hometown_or_elsewhere=='hometown'):
    #         eligible_ltc_user.hometown_ltc_availed+=1
    #     if(application.is_hometown_or_elsewhere=='elsewhere' ):
    #         eligible_ltc_user.elsewhere_ltc_availed+=1

    #     eligible_ltc_user.save()
    #     application.save()
    #     # add notif
    #     messages.success(request, 'Status updated successfully!')
    
    
    elif 'ltc_new_eligible_user' in request.POST:
        try:
            username = request.POST.get('username')

            if not User.objects.filter(username=username).exists():
                messages.error(request, 'The given user does not exist')
                return

            user_id = User.objects.get(username=username)
            if Ltc_eligible_user.objects.filter(user=user_id).exists():
                messages.error(request, 'This user is already eligible for availing LTC')
                return

            joining_date = request.POST.get('joining_date')
            current_block_size = request.POST.get('current_block_size')
            total_ltc_allowed = request.POST.get('total_ltc_allowed')
            hometown_ltc_allowed = request.POST.get('hometown_ltc_allowed')
            elsewhere_ltc_allowed = request.POST.get('elsewhere_ltc_allowed')
            hometown_ltc_availed = request.POST.get('hometown_ltc_availed')
            elsewhere_ltc_availed = request.POST.get('elsewhere_ltc_availed')

            eligible_user = Ltc_eligible_user.objects.create(
                user = user_id,
                date_of_joining = joining_date,
                current_block_size = current_block_size,
                total_ltc_allowed = total_ltc_allowed,
                hometown_ltc_allowed = hometown_ltc_allowed,
                elsewhere_ltc_allowed = elsewhere_ltc_allowed,
                hometown_ltc_availed = hometown_ltc_availed,
                elsewhere_ltc_availed = elsewhere_ltc_availed
            )
            messages.success(request, 'New LTC eligible user succesfully created')
        except Exception as e:
            messages.error(request,e)

    elif 'ltc_edit_eligible_user' in request.POST:
        try:
            username = request.POST.get('username')
            if not User.objects.filter(username=username).exists():
                messages.error(request, 'The given user does not exist')
                return

            user_id = User.objects.get(username=username)
            joining_date = request.POST.get('joining_date')
            current_block_size = request.POST.get('current_block_size')
            total_ltc_allowed = request.POST.get('total_ltc_allowed')
            hometown_ltc_allowed = request.POST.get('hometown_ltc_allowed')
            elsewhere_ltc_allowed = request.POST.get('elsewhere_ltc_allowed')
            hometown_ltc_availed = request.POST.get('hometown_ltc_availed')
            elsewhere_ltc_availed = request.POST.get('elsewhere_ltc_availed')

            eligible_user = Ltc_eligible_user.objects.select_related('user').get(user=user_id)
            eligible_user.date_of_joining = joining_date
            eligible_user.current_block_size = current_block_size
            eligible_user.total_ltc_allowed = total_ltc_allowed
            eligible_user.hometown_ltc_allowed = hometown_ltc_allowed
            eligible_user.elsewhere_ltc_allowed = elsewhere_ltc_allowed
            eligible_user.hometown_ltc_availed = hometown_ltc_availed
            eligible_user.elsewhere_ltc_availed = elsewhere_ltc_availed
            eligible_user.save()
            messages.success(request, 'Eligible LTC user details successfully updated.')
        except Exception as e:

Fusion-main/FusionIIIT/templates/establishment/common.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
Establishment
{% endblock %}

{% block css %}
<meta name='viewport' content='width=device-width, initial-scale=1'>
{% endblock %}

{% block body %}
{% block navBar %}
{% include 'dashboard/navbar.html' %}
{% endblock %}


{% comment %}The grid starts here!{% endcomment %}
<div class="ui stackable doubling grid">

    {% comment %}The left-margin segment!{% endcomment %}
    <div class="column"></div>

    {% comment %} The left-rail segment starts here! {% endcomment %}
    <div class="three wide column">

        {% comment %}The user image card starts here!{% endcomment %}
        {% block usercard %}
        {% include 'globals/usercard.html' %}
        {% endblock %}
        {% comment %}The user image card ends here!{% endcomment %}

        <div class="ui divider"></div>
        {% block sidetabmenu %}
        {% endblock %}

    </div>
    {% comment %} The left-rail segment ends here! {% endcomment %}

    {% comment %} The central-rail segment starts here! {% endcomment %}
    <div class="eight wide column">
        <!-- {% comment %}
        TODO: Loader required?
        <div class="ui active large text loader" id="loader">
            Loading ...
        </div> -->
        <!-- {% endcomment %} -->
        {% block content %}
        {% endblock %}
    </div>
    {% comment %}The central-rail segment ends here!{% endcomment %}

    {% comment %}The right-rail segment starts here!{% endcomment %}
    <div class="three wide column">
        <div class="row">
            {% comment %}
            TODO: the right rail!
            {% endcomment %}
            {% block rightcontent %}
            {% endblock %}
        </div>
    </div>
    {% comment %}The right-rail segment ends here!{% endcomment %}

    {% comment %}The right-margin segment!{% endcomment %}
    <div class="column"></div>

</div>
{% comment %}The grid ends here!{% endcomment %}


{% endblock %}

{% block javascript %}

{% endblock %}

Fusion-main/FusionIIIT/templates/establishment/cpda_admin.html
{% extends 'establishment/common.html' %}

{% block sidetabmenu %}
{% comment %}The Tab-Menu starts here!{% endcomment %}
<div class="ui huge fluid vertical pointing menu" style="max-width: 320px;">
  <a class="item" href="{% url 'establishment:ltc' %}">
    LTC
    <i class="right floated chevron right icon"></i>
  </a>
  {% if request.user.extrainfo.user_type == 'faculty' or director %}
  <a class="item active" href="{% url 'establishment:cpda' %}">
    CPDA
    <i class="right floated chevron right icon"></i>
  </a>
  {% endif %}
  <a class="item" href="{% url 'establishment:appraisal' %}">
    Appraisal
    <i class="right floated chevron right icon"></i>
  </a>
</div>
{% comment %}The Tab-Menu ends here!{% endcomment %}
{% endblock %}

{% block content %}
{% load semanticui %}
{% load static %}
{% block cpda %}
<div class="ui top attached tabular menu">
    <a class="item active" data-tab="cpdaone">
        Pending
    </a>
    <a class="item" data-tab="cpdatwo">
        Reviewed
    </a>
</div>

<style>
    * { font: 17px Calibri; }
    table { width: 70%; }
    table, th, td { border: solid 1px #DDD;
        border-collapse: collapse; padding: 2px 3px; text-align: center;
    }
    th {background-color:#f1f1c1}
  .req:after {
    content:" *";
    color: red;
  }
</style>
<!--
pending cpda applications 
-->
<div class="ui active tab segment" data-tab="cpdaone">
    <div class="content">
        <div class="description">
            <div class="ui items">
                {% for app in cpda_to_review_apps %}
                    <div class="item">
                        <div class="content">

                            <a class="header">Application id : {{app.id}}</a>
                            <div class="meta"> 
                                <span>Applicant : {{app.applicant.first_name}}</span>
                            </div>
                            <div>
                                <button class="ui large primary button" onclick="$('.ui.modal.assign_cpda-{{app.id}}').modal('show')">
                                    View
                                </button>
                            </div>
                        </div>
                    </div>
                
                    <div class="ui modal assign_cpda-{{app.id}}">
                        <i class="close icon"></i>
                        <div class="header">
                            CPDA 
                        </div>
                        <div class="content">
                            <div class="description">
                                <!-- Add condition if it's requested or adj_pending -->
                                <label>Application id : {{ app.id }}</label><br>
                                <label>Applicant : {{ app.applicant.first_name }}</label><br>
                                <label>Status : {{ app.status|title }}</label><br>
                                <label>PF Number : {{ app.pf_number }}</label><br>
                                <label>Requested Advance : {{ app.requested_advance }}</label><br>
                                <label>Purpose : {{ app.purpose }}</label><br>
                                {% if app.status == 'adjustments_pending' %}
                                    <label>Adjustment Amount : ₹ {{app.adjustment_amount}}</label><br>
                                    <label>Total Bills Amount : ₹ {{app.total_bills_amount}}</label><br>
                                    {% if app.tracking_info.bill %}
                                    <label>Bill :  <a href="{{app.tracking_info.bill.url}}"> CLick to View Bill</a></label><br>
                                    {%endif%}
                                {% endif %}
                                <br>
                                <label>HOD Remarks : {{ app.tracking_info.remarks_rev1 }}</label><br>

                                <!-- Add form here -->
                                <form class="ui large form" method="post" enctype="multipart/form-data" id="form1">
                                    {% csrf_token %}
                                    {% render_field app.reviewform.app_id %} 
                                    <div class="field">
                                        {% render_field app.reviewform.remarks %} 
                                    </div>
                                    <button type="submit" name="cpda_assign_form" class="ui large primary button">
                                        Verify
                                    </button>
                                    
                                </form>
                            </div>
                        </div>
                        <div class="actions">
                            <div class="ui black deny button">
                                Cancel
                            </div>
                        </div>
                    </div>
                    {% empty %}
                        <tr><td colspan="3">No Pending Application</td><tr>
                            <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


<!--
Reviewed cpda applications 
-->
<div class="ui tab segment" data-tab="cpdatwo">
    <div class="content">
        <div class="description">
            <div class="ui items">
                {% for app in cpda_reviewed_apps %}
                    <div class="item">
                        <div class="content">
                            <a class="header">Status : {% if app.status == 'requested' %} Verified {% elif app.status == 'finished' %} Adjustments Approved {%else%}{{app.status|title}} {%endif%}</a>
                            <div class="meta">
                                <span>Requested Advance : ₹ {{app.requested_advance}}</span>
                            </div>
                            <div class="meta"> Purpose : {{app.purpose}}</div>
                            <div>
                                <button class="ui large primary button" onclick="$('.ui.modal.view_cpda-{{app.id}}').modal('show')">
                                    View
                                </button>
                                
                            </div>
                        </div>
                    </div>
                
                    <div class="ui modal view_cpda-{{app.id}}">
                        <i class="close icon"></i>
                        <div class="header">
                            View CPDA
                        </div>
                        <div class="content">
                            <div class="description">
                                <label>Application id : {{ app.id }}</label><br>
                                <label>Applicant : {{ app.applicant.first_name }}</label><br>
                                <label>Status : {{ app.status|title }}</label><br>
                                <label>PF Number : {{ app.pf_number }}</label><br>
                                <label>Requested Advance : {{ app.requested_advance }}</label><br>
                                <label>Purpose : {{ app.purpose }}</label><br>
                                <label>HOD Remarks : {{app.tracking_info.remarks_rev1}}</label><br>
                                <label>Your Remarks : {{app.tracking_info.remarks_rev2}}</label><br>
                                
                                {% if app.status == 'finished' or app.status == 'adjustments_pending' %}

                                    <label>Adjustment Amount : {{ app.adjustment_amount }}</label><br>
                                    <label>No. of Bills : {{ app.bills_attached }}</label><br>
                                    <!-- add preview of bills here  -->
                                    <label>Total amount of Bills : {{ app.total_bills_amount }}</label><br>
                                    {% if app.tracking_info.bill %}
                                    <label>Bill :  <a href="{{app.tracking_info.bill.url}}"> CLick to View Bill</a></label><br>
                                    {%endif%}
                                {% endif %}
                            </div>
                        </div>
                        <div class="actions">
                            <div class="ui black deny button">
                                Cancel
                            </div>
                        </div>
                    </div>
                    {% empty %}
                        <tr><td colspan="3">No Reviewed Application</td><tr>
                            <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% endblock %}

{% block javascript %}
<script>

</script>
{% endblock %}

Fusion-main/FusionIIIT/templates/establishment/hr1_form.html
    <div>

        {% if cpda %}
        {% if admin %}
        {% include 'establishment/cpda_admin.html' %}
        {% elif reviewer %}
        {% include 'establishment/cpda_reviewer.html' %}
        {% else %}
        {% include 'establishment/cpda.html' %}
        {% endif %}
        {% elif ltc %}
        {% if admin %}
        {% include 'establishment/ltc_admin.html' %}
        {% else %}
        {% include 'establishment/ltc.html' %}
        {% endif %}
        {% elif appraisal %}
        {% if hod %}
        {% include 'establishment/appraisal_hod.html' %}
        {% elif director %}
        {% include 'establishment/appraisal_director.html' %}
        {% elif admin %}
        {% include 'establishment/appraisal_admin.html' %}
        {% else %}
        {% include 'establishment/appraisal.html' %}
        {% endif %}
        {% endif %}
        </div>
     
    
    