Fusion-main/FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fusion-main/FusionIIIT/applications/library/urls.py
from django.conf.urls import url

from . import views

app_name = 'library'

urlpatterns = [

    url(r'^library/$', views.libraryModule, name='libraryModule'),

]

Fusion-main/FusionIIIT/templates/libraryModule/alerts.html
{% load static %}

{% block alerts %}
    <div class="ui centered cards" style="padding: 2px">

        {% comment %}A single card starts here!{% endcomment %}
        <div class="ui card">
            <div class="content">
                <img class="right floated circular ui image" src="{% static 'globals/img/zlatan.jpg' %}" style="width: 50px; height: auto;">
                <div class="header">
                    Dr. Vinod Kumar Jain
                </div>
                <div class="meta">
                    Associate Professor
                </div>

                <div class="ui divider"></div>

                <div class="description">

                    <span>Accession#</span>
                    <span class="right floated">...</span>

                    <br>

                    <span>Due Date</span>
                    <span class="right floated">...</span>

                    <br>

                </div>
            </div>

            <div class="extra content">
                <span style="color: #000;">Fine</span>
                <span class="right floated" style="color: #000;">&#8377;...</span>
            </div>
        </div>
        {% comment %}A single card starts here!{% endcomment %}

    </div>
{% endblock %}

Fusion-main/FusionIIIT/templates/libraryModule/authornamesearch.html
{% load static %}
<div class="ui active accordion field">
    <form name ="authorform"class="ui form" method="POST" action="{% url 'library:libraryModule' %}">
      {% csrf_token %}
      <div class="field">
        <label>Author Name</label>
        <input type="text" name="authorname" placeholder="Author Name">
      </div>
      <input type="hidden" value="authorname" name="nametype" />
      <button class="ui primary button"onclick="return validateAuthor()" type="submit">Search</button>
    </form>
    {% if bookresults %}
      {% if bookresults != 'N' %}
      {% for a in bookresults %}
        {{ a }}
        <br>
        {% endfor %}

    {% elif bookresults == 'N' %}
       <br>
       <center><h4>No Results Found!</h4></center>

    {% endif %}
    {% endif %}
</div>

<script type="text/javascript">
  function validateAuthor() {
    var text = document.forms["authorform"]["authorname"].value;
    if (text == "") {
      alert("Please Enter Author Name");
      return false;
    }
    return true;
  }
</script>

Fusion-main/FusionIIIT/templates/libraryModule/booknamesearch.html
{% load static %}
<div class="ui active accordion field">
    <form name="bookform"  class="ui form" method="POST"  action="{% url 'library:libraryModule' %}" >
      {% csrf_token %}
      <div class="field">
        <label>Book Name</label>
        <input type="text" name="bookname" placeholder="Book Name" class="harshitt">
      </div>
      <input type="hidden" value="bookname" name="nametype" />
      <button class="ui primary button harshitb" onclick="return validateBook()" type="submit">Search</button>
    </form>
    {% if bookresults %}
      {% if bookresults != 'N' %}
      {% for a in bookresults %}
        {{ a }}
        <br>
        {% endfor %}

    {% elif bookresults == 'N' %}
       <br>
       <center><h4>No Results Found!</h4></center>
    
    {% endif %}
    {% endif %}
</div>


<script type="text/javascript">
  function validateBook() {
    var text = document.forms["bookform"]["bookname"].value;
    if (text == "") {
      alert("Please Enter Book Name");
      return false;
    }
    return true;
  }
</script>

Fusion-main/FusionIIIT/templates/libraryModule/booksearch.html
{% block tab3 %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="tab1content1">
            Book Search
        </a>

    </div>
    <div class="ui two item menu">
        <a class="{% if officer_statistics_past_pbi_search or officer_statistics_past_pbi_add or officer_statistics_past_higher_search or officer_statistics_past_higher_add %}item{% else %}active item{% endif %}" data-tab="bookname">
          Book Name
        </a>

        <a class="{% if officer_statistics_past_pbi_search or officer_statistics_past_pbi_add %}active item{% else %}item{% endif %}" data-tab="authorname">
          Author Name
        </a>
    </div>

    <div class="ui active tab segment" data-tab="bookname">
        <div class="ui vertical segment">
            {% block bookname %}
                {% include 'libraryModule/booknamesearch.html' %}
            {% endblock %}
        </div>
    </div>

    <div class="ui tab segment" data-tab="authorname">
      <div class="ui vertical segment">
          {% block authorname %}
              {% include 'libraryModule/authornamesearch.html' %}
          {% endblock %}
      </div>
    </div>

{% endblock tab3%}

Fusion-main/FusionIIIT/templates/libraryModule/dues.html
{% block tab2 %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="tab2content1">
            Dues
        </a>
    </div>

    <div class="ui active tab" data-tab="tab2content1">
        <div class="ui vertical segment">
            {% block tab2content1 %}
                {% include 'libraryModule/dues_content.html' %}
            {% endblock %}
        </div>
    </div>
{% endblock tab2%}

Fusion-main/FusionIIIT/templates/libraryModule/dues_content.html
<h4> Dues On Non returned Items </h4>
<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%; padding-right: 2.5%;padding-top: 1%; padding-bottom: 1.5%; text-align: center; margin: auto;">
    <thead>
    <tr>
        <th class="five wide column">
            Accession Number
        </th>

        <th class="five wide column">
            Due Date
        </th>


        <th>
            Days * ODC
        </th>
        <th>
            Total ODC
        </th>
    </tr>
    </thead>

    <tbody>
    {% for key, values in data2.items %}
    <tr>
      <td>{{values.assn}}</td>
      <td>{{values.due_date}}</td>
      
      <td>{{values.tdod}}</td>
      <td>{{values.tod}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<h4> Dues On returned Items </h4>
<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%; padding-right: 2.5%;padding-top: 1%; padding-bottom: 1.5%; text-align: center; margin: auto;">
    <thead>
    <tr>
        <th class="four wide column">
            Accession Number
        </th>

        <th class="five wide column">
            Due Date
        </th>

        <th class="five wide column">
            Return Date
        </th>

        <th>
            Days * ODC
        </th>
        <th>
            Total ODC
        </th>
        <th>
            Cause
        </th>
    </tr>
    </thead>

    <tbody>
    {% for key, values in data3.items %}
    <tr>
      <td>{{values.assn}}</td>
      <td>{{values.due_date}}</td>
      <td>{{values.return_date}}</td>
      <td>{{values.tdod}}</td>
      <td>{{values.tod}}</td>
      <td>{{values.cause}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<br>
<div class="ui divider"></div>
<h5> ODC : Over Due Charge </h5>

Fusion-main/FusionIIIT/templates/libraryModule/history.html
{% block tab3 %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="tab3content1">
            Issue History
        </a>
    </div>

    <div class="ui active tab" data-tab="tab3content1">
        <div class="ui vertical segment">
            {% block tab3content1 %}
                {% include 'libraryModule/history_content.html' %}
            {% endblock %}
        </div>
    </div>
{% endblock tab3%}

Fusion-main/FusionIIIT/templates/libraryModule/history_content.html
<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%; padding-right: 2.5%;padding-top: 1%; padding-bottom: 1.5%; text-align: center; margin: auto;">
    <thead>
    <tr>
        <th class="four wide column">
            Accession Number
        </th>

        <th class="six wide column">
            Book Name
        </th>

        <th>
            Due Date
        </th>

        <th>
            Return Date
        </th>

        <th>
            Days left
        </th>
    </tr>
    </thead>

    <tbody>
    <tr>
        <td>
            ...
        </td>

        <td>
            ...
        </td>

        <td>
            ...
        </td>

        <td>
            ...
        </td>

        <td>
            ...
        </td>
    </tr>

    </tbody>
</table>

<br>
<div class="ui divider"></div>

Fusion-main/FusionIIIT/templates/libraryModule/issuedItems.html
{% block tab1 %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="tab1content1">
            Issued Items
        </a>
                     
    </div>

    <div class="ui active tab segment" data-tab="tab1content1">
        <div class="ui vertical segment">
            {% block tab1content1 %}
                {% include 'libraryModule/issuedItems_content.html' %}
            {% endblock %}
        </div>
    </div>
        

   

{% endblock tab1%}

Fusion-main/FusionIIIT/templates/libraryModule/issuedItems_content.html
<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%; padding-right: 2.5%;padding-top: 1%; padding-bottom: 1.5%; text-align: center; margin: auto;">
    <thead>
    <tr>
        <th class="four wide column">
            Accession Number
        </th>

        <th class="six wide column">
            Book Name
        </th>

        <th>
            Due Date
        </th>

        <th>
            Issue Date
        </th>

        
    </tr>
    </thead>

    <tbody>
    
   {% for key, values in data1.items %}
   <tr>
        <td>{{ values.assn }}</td> 
        <td>{{ values.book_name }}</td> 
        <td>{{ values.due_date }}</td> 
        <td>{{ values.issue_date }}</td>      
    </tr>
    {% endfor %}

    </tbody>
</table>

<br>
<div class="ui divider"></div>

Fusion-main/FusionIIIT/templates/libraryModule/libraryModule.html
{% extends 'globals/base.html' %}
{% load static %}


{% block title %}
    Module
{% endblock %}


{% block body %}
    {% block navBar %}
        {% include 'dashboard/navbar.html' %}
    {% endblock %}

    {% comment %}The grid starts here!{% endcomment %}
    <div class="ui stackable doubling grid">

        {% comment %}The left-margin segment!{% endcomment %}
        <div class="column"></div>

        {% comment %}
            The left-rail segment starts here!
        {% endcomment %}
        <div class="three wide column">

            {% comment %}The user image card starts here!{% endcomment %}
            {% block usercard %}

                {% comment %}
                TODO: Instead of Name write the position like "Office Of Dean Students!"
                {% endcomment %}

                {% include 'globals/usercard.html' %}
            {% endblock %}
            {% comment %}The user image card ends here!{% endcomment %}

            <div class="ui divider"></div>

            {% comment %}The Tab-Menu starts here!{% endcomment %}
            <div class="ui huge fluid vertical pointing menu"
                 style="max-width: 320px;">

                 <a class="active item" data-tab="third">
                   Book Search
                   <i class="right floated chevron right icon"></i>
                </a>

                <a class="item" data-tab="first">
                    Issued Items
                    <i class="right floated chevron right icon"></i>
                </a>

                <a class="item" data-tab="second">
                    Dues
                    <i class="right floated chevron right icon"></i>
                </a>



            </div>
            {% comment %}The Tab-Menu ends here!{% endcomment %}

        </div>
        {% comment %}
            The left-rail segment ends here!
        {% endcomment %}


        {% comment %}
            The central-rail segment starts here!
        {% endcomment %}
        <div class="eight wide column">
            <div class="ui tab segment" data-tab="first">
                {% block tab1 %}
                    {% include 'libraryModule/issuedItems.html' %}
                {% endblock %}
            </div>


            <div class="ui tab segment" data-tab="second">
                {% block tab2 %}
                    {% include 'libraryModule/dues.html' %}
                {% endblock %}
            </div>


            <div class="ui active tab segment" data-tab="third">
                {% block tab3 %}
                    {% include 'libraryModule/booksearch.html' %}
                {% endblock %}
            </div>

        </div>
        {% comment %}The central-rail segment ends here!{% endcomment %}

        {% comment %}The right-rail segment starts here!{% endcomment %}
        <div class="three wide column">
            <div class="row">
                <div class="ui row">
                    <div class="ui card" style=" margin: 8px; margin-left: 16px;">
                        <div class="content">
                            <div class="description">
                                <h3>
                                    <span>Total Due</span>
                                    <span class="right floated">&#8377; {{ due }}</span>
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

                    </div>
                </div>
            </div>
        </div>
        {% comment %}The right-rail segment ends here!{% endcomment %}

        {% comment %}The right-margin segment!{% endcomment %}
        <div class="column"></div>

    </div>
    {% comment %}The grid ends here!{% endcomment %}



{% endblock %}

{% block javascript %}

    <script src="https://cdn.rawgit.com/mdehoog/Semantic-UI/6e6d051d47b598ebab05857545f242caf2b4b48c/dist/semantic.min.js"></script>
    <script type="text/javascript" src="{% static 'globals/js/datepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'globals/js/tablesort.js' %}"></script>


    <script>
        $(document).ready(function(){
            $("#textLoader").toggle();
            $("#replacement-card").toggle();
            setTimeout(loader, 1750);
        });

        function loader() {
            $("#textLoader").toggle();
            $("#replacement-card").toggle();
            $("#loader").removeClass("active");
            $("#loader").addClass("disabled");
        }
    </script>

{% endblock %}

Fusion-main/FusionIIIT/templates/libraryModule/tab1content2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>