Fusion-main/FusionIIIT/Fusion/urls.py
import notifications.urls
import debug_toolbar
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls')),
    url(r'^aims/', include('applications.academic_information.urls')),
    url(r'^notifications/', include('applications.notifications_extension.urls')),
    url(r'^estate/', include('applications.estate_module.urls')),
    url(r'^dep/', include('applications.department.urls')),
    url(r'^programme_curriculum/',include('applications.programme_curriculum.urls')),
    url(r'^iwdModuleV2/', include('applications.iwdModuleV2.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^research_procedures/', include('applications.research_procedures.urls')),
    url(r'^accounts/', include('allauth.urls')),


    url(r'^eis/', include('applications.eis.urls')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^purchase-and-store/', include('applications.ps1.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^establishment/', include('applications.establishment.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^counselling/', include('applications.counselling_cell.urls')),
    url(r'^hostelmanagement/', include('applications.hostel_management.urls')),
    url(r'^income-expenditure/', include('applications.income_expenditure.urls')),
    url(r'^hr2/', include('applications.hr2.urls')),
    url(r'^recruitment/', include('applications.recruitment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fusion-main/FusionIIIT/applications/eis/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'eis'
urlpatterns = [
    # url used to add data
    url(r'uploadcsv/$', views.upload_file),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^rspc_profile/$', views.rspc_profile, name='rspc_profile'),

    #delete
    url(r'^achv/(?P<pk>[0-9]+)/$', views.achievementDelete, name='achievement_delete'),
    url(r'^emp_confrence_organisedDelete/(?P<pk>[0-9]+)/$', views.emp_confrence_organisedDelete, name='emp_confrence_organisedDelete'),
    url(r'^emp_consultancy_projectsDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_consultancy_projectsDelete, name='emp_consultancy_projectsDelete'),

    #url(r'^emp_confrence_organisedDelete/(?P<sr>[0-9]+)/$', views.emp_confrence_organisedDelete, name='emp_confrence_organisedDelete'),
    url(r'^emp_event_organizedDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_event_organizedDelete, name='emp_event_organizedDelete'),
    url(r'^emp_expert_lecturesDelete/(?P<pk>[0-9]+)/$', views.emp_expert_lecturesDelete, name='emp_expert_lecturesDelete'),
    url(r'^emp_keynote_addressDelete/(?P<pk>[0-9]+)/$', views.emp_keynote_addressDelete, name='emp_keynote_addressDelete'),
    url(r'^emp_mtechphd_thesisDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_mtechphd_thesisDelete, name='emp_mtechphd_thesisDelete'),
    url(r'^emp_patentsDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_patentsDelete, name='emp_patentsDelete'),
    url(r'^emp_published_booksDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_published_booksDelete, name='emp_published_booksDelete'),
    url(r'^emp_research_papersDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_research_papersDelete, name='emp_research_papersDelete'),
    url(r'^emp_research_projectsDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_research_projectsDelete, name='emp_research_projectsDelete'),
    url(r'^emp_session_chairDelete/(?P<pk>[0-9]+)/$', views.emp_session_chairDelete, name='emp_session_chairDelete'),

    url(r'^emp_techtransferDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_techtransferDelete, name='emp_techtransferDelete'),
    url(r'^emp_visitsDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_visitsDelete, name='emp_visitsDelete'),
    url(r'^emp_consymDelete/(?P<pk>[0-9]+)/(?P<sr>[0-9]+)/(?P<mark>[0-9]+)/$', views.emp_consymDelete, name='emp_consymDelete'),


    # edit personal information
    url(r'^persinfo/$', views.persinfo, name='persinfo'),
    url(r'^journal/edit$', views.editjournal, name='editjournal'),
    url(r'^foreignvisit/edit$', views.editforeignvisit, name='editforeignvisit'),
    url(r'^indianvisit/edit$', views.editindianvisit, name='editindianvisit'),
    url(r'^consym/edit$', views.editconsym, name='editconsym'),
    url(r'^event/edit$', views.editevent, name='editevent'),
    url(r'^conference/edit$', views.editconference, name='editconference'),
    url(r'^books/edit$', views.editbooks, name='editbooks'),

    # insert
    url(r'^pg/$', views.pg_insert, name='pg_insert'),
    url(r'^phd/$', views.phd_insert, name='phd_insert'),
    url(r'^fvisit/$', views.fvisit_insert, name='fvisit_insert'),
    url(r'^ivisit/$', views.ivisit_insert, name='ivisit_insert'),
    url(r'^journal/$', views.journal_insert, name='journal_insert'),
    url(r'^conference/$', views.conference_insert, name='conference_insert'),
    url(r'^book/$', views.book_insert, name='book_insert'),
    url(r'^consym/$', views.consym_insert, name='consym_insert'),
    url(r'^event/$', views.event_insert, name='event_insert'),
    url(r'^award/$', views.award_insert, name='award_insert'),
    url(r'^talk/$', views.talk_insert, name='talk_insert'),
    url(r'^chaired/$', views.chaired_insert, name='chaired_insert'),
    url(r'^keynote/$', views.keynote_insert, name='keynote_insert'),
    url(r'^project/$', views.project_insert, name='project_insert'),
    url(r'^consult_insert/$', views.consult_insert, name='consult_insert'),
    url(r'^patent_insert/$', views.patent_insert, name='patent_insert'),
    url(r'^transfer_insert/$', views.transfer_insert, name='transfer_insert'),

    # generate report
    url(r'^report/$', views.generate_report, name='generate_report'),
    url(r'^rspc_report/$', views.rspc_generate_report, name='rspc_generate_report'),

    #api urls
    url(r'^api/', include('applications.eis.api.urls')),

]

Fusion-main/FusionIIIT/templates/eisModulenew/conference.html
{% load static %}
{% block conference %}

 <div class="ui pointing secondary menu">
        <a class="active item" data-tab="Conference/Symposium">
            Conference/Symposium
        </a>

       
    </div>

 <div class="ui active tab segment" data-tab="Conference/Symposium">
    {% if request.user == user %}
       <h4 class="ui dividing header">Add a Conference/Symposium</h4>
        <form class="ui form" id="conferenceform2" name="conferenceform2" method="POST" action="{% url 'eis:consym_insert' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field">
                 <div class="three fields">
                    <div class="field">
                        <label>Role </label>
                         <!--  <input placeholder="Published" type="text"> -->
                        <!-- code change starts --> 
                              <div class="ui fluid search selection dropdown">
                                <input type="hidden" id="conference_role" name="conference_role">
                                <i class="dropdown icon"></i>
                                <div class="default text">Role</div>
                                <div class="menu">
                                     <div class="item" data-value="Organised" onclick="myFunction3(); myFunction4();">Organised</div>
                                    <div class="item" data-value="Conference Chair" onclick="myFunction3(); myFunction5();">Conference Chair</div>
                                    <div class="item" data-value="Advisory Committee" onclick="myFunction3(); myFunction5();">Advisory Committee</div>
                                    <div class="item" data-value="Program Committee" onclick="myFunction3(); myFunction5();">Program Committee</div> 
                                    <div class="item" data-value="Any other" onclick="myFunction2(); myFunction5();">Any other</div>
                                   
                                </div>
                        </div>
                    </div>
                      <div class=" field">
                               <label><br></label>
                             <input placeholder="please specify"  type="text" id="myDIV1" name="myDIV1" style="display:none;">
                        </div>
                     
                           <div class="field">
                            <label><br> </label>
                             <!--  <input placeholder="Published" type="text"> -->
                            <!-- code change starts --> 
                                  <div class="ui fluid search selection dropdown" id="myDIV2" name="myDIV2"  style="display:none;">
                                <input type="hidden" id="conference_organised" name="conference_organised">
                                <i class="dropdown icon"></i>
                                <div class="default text">Organised</div>
                                <div class="menu">
                                    <div class="item" data-value="Chairman/Chairperson" onclick="myFunction3();">Chairman/Chairperson</div>
                                    <div class="item" data-value="Convener"onclick="myFunction3();">Convener</div>
                                    <div class="item" data-value="Co-ordinator" onclick="myFunction3();">Co-ordinator</div>
                                    <div class="item" data-value="Secretary"onclick="myFunction3();" >Secretary</div>
                                    <div class="item" data-value="Joint-Secretary" onclick="myFunction3();">Joint-Secretary</div>
                                    <div class="item" data-value="Joint Secretary-Cum Treasurer" onclick="myFunction3();">Joint Secretary-Cum Treasurer </div>
                                    <div class="item" data-value="Treasure" onclick="myFunction3();">Treasurer</div>
                                     <div class="item" data-value="Any other" onclick="myFunction2();">Any other</div>

                                   
                                </div>
                            </div>
                        </div>
                     <!-- code change ends --> 
                   
                </div>
            </div>

            <div class="field">
                
                
                    <div class=" three fields">
                          
                            <div class="field">
                                     <label>Venue</label>
                                     <input placeholder="" type="text" id="conference_venue" name="conference_venue">
                                </div>
                        
                       
                            <div class="field">
                                    <label>Start Date</label>
                                     <!--  <input placeholder="" type="text"> -->
                                        <!-- code change starts --> 
                                 <div class="ui calendar" id="rangestart5">
                                      <div class="ui input left icon">
                                        <i class="calendar icon"></i>
                                        <input type="text" placeholder="Start" name="conference_start_date" id="conference_start_date">
                                      </div>
                                </div>
                                <!-- code change ends -->
                             </div>
                      
                       
                            <div class="field">
                                    <label>End Date</label>
                                     <!-- <input placeholder="" type="text"> -->
                                        <!-- code change starts --> 
                                         <div class="ui calendar" id="rangestart6">
                                              <div class="ui input left icon">
                                                <i class="calendar icon"></i>
                                                <input type="text" placeholder="End" id="conference_end_date" name="conference_end_date">
                                              </div>
                                        </div>
                                <!-- code change ends -->
                                </div>
            </div>


                <div class="fields">
               <!-- code change starts --> 
                 <div class="fourteen wide field">
                        <label>Conference Name</label>
                        <input placeholder="Co-author" type="text" id="conference_name" name="conference_name">
                    </div>
            <!-- code change ends-->    

                    <div class="two wide field">
                        <label><br></label>
                        <button class="ui right floated primary button" id="saveconference2" name="saveconference2"  style="display: block;">
                            Save
                            <i class="ui save icon right floated"></i>
                        </button>
                        <button class="ui right floated primary button" id="editconference2" name="editconference2" style="display: none;">
                            Update
                            <i class="ui edit icon right floated"></i>
                        </button>
                        <input type="text" id="conferencepk2" name="conferencepk2" hidden>
                        <input type="text" id="index13" name="index13" hidden>
                    </div> 
                </div>

                 
            </div>
        </form>
        <br>{% endif %}
        <h4 class="ui dividing header">Report:</h4>
        <div class="pagination">
                <h4> <span class="step-links" >
                    {% if confs.has_previous %}
                        <a href="?page13=1" >&laquo; first</a>
                        <a href="?page13={{ confs.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ confs.number }} of {{ confs.paginator.num_pages }}.
                    </span>

                    {% if confs.has_next %}
                        <a href="?page13={{ confs.next_page_number }}">next</a>
                        <a href="?page13={{ confs.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span></h4>
            </div>
    <!-- scrollbar -->
    <div style="width: 45vw; height: 500px; overflow-y: scroll">
        <table class="ui celled table">
            <thead>
            <tr>
                <th class="sorted ascending">Sr.</th>
                <th class="">Role</th>
                <th class="">Conference Name</th>
                <th class="">Venue</th>
                <th class="">Start Date & End Date</th>
                <th class="">Action</th>
            </tr>
            </thead>

            <tbody>
                {% for e in consymps %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {% if e.role1 == "Organised" %}
                                {{ e.role1 }} - {{ e.role2 }}
                            {% else %}
                                {{ e.role1 }}
                            {% endif %}
                            
                        </td>
                        <td>{{ e.name }}</td>
                        <td>{{ e.venue }}</td>
                        <td>{{ e.start_date }} - {{ e.end_date }}</td>
                        {% if request.user == user %}
                            <td>
                                <button type="button"
                                   id="editButton13"
                                   class="ui button left floated" onclick="editconference2(
                                    '{{ forloop.counter }}','{{ e.pk }}', {% if e.role1 == 'Organised' %}
                                    '{{e.role1}}', '{{e.role2}}', 
                                    {% else %} '{{e.role1}}', 'None', 
                                    {% endif %}
                                    '{{e.name}}', '{{e.venue}}',
                                    '{{e.start_date}}', '{{e.end_date}}')"
                                   >
                                   <i class="ui black edit icon"></i>
                                </button>
                                <a href="{% url 'eis:emp_consymDelete' e.pk forloop.counter 13%}"
                                   id="editButton"
                                   class="ui blue button left floated" onclick=""
                                   value = "Delete">
                                   <i class="ui red delete icon"></i>
                                </a>
                                
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}

            </tbody>

        </table>
    </div>
        <div class="pagination">
                <h4> <span class="step-links" >
                    {% if confs.has_previous %}
                        <a href="?page13=1" >&laquo; first</a>
                        <a href="?page13={{ confs.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ confs.number }} of {{ confs.paginator.num_pages }}.
                    </span>

                    {% if confs.has_next %}
                        <a href="?page13={{ confs.next_page_number }}">next</a>
                        <a href="?page13={{ confs.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span></h4>
            </div>
        
    </div>
    {% endblock %}
    

Fusion-main/FusionIIIT/templates/eisModulenew/others.html
{% load static %}

{% block others %}
    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="{% if mark15 != 1 %}active item {% else %} item {% endif %}" data-tab="other1">
            Achievements
        </a>

        <a class="{% if mark15 == 1 %}active item {% else %} item {% endif %}" data-tab="other2">
            Experts Lectures/Invited Talks
        </a>

       
        <!-- <a class="item" data-tab="other3">
            Keynote/Planery Address
        </a>

        <a class="item" data-tab="other4">
            Session Chaired
        </a> -->
    </div>


    {% comment %}The  Achievement segment starts here!{% endcomment %}
    <div class="{% if mark15 != 1 %}ui active tab segment {% else %} ui tab segment {% endif %}" data-tab="other1">
        <h4 class="ui dividing header" id="changes12">Add an Achievement</h4>
            <form class="ui form"  method="post" action="{% url 'eis:award_insert' %}" onsubmit="return validateaward()">
            {% csrf_token %}
           
            <div style="display: none;"> <input type="text" id="achZ" name="ach_id"></div>
            <div class="field">
                <label>Year/Month/Day</label>
                <div class=" four fields">
                    <div class=" field">
                        <!-- <input placeholder="Year/Month/Day" type="text"> -->
                             <div class="ui fluid search selection dropdown">
                            <input type="hidden" name="a_day"  id="achC"  >
                            <i class="dropdown icon"></i>
                            <div class="default text">Select Day</div>
                            <div class="menu">
                                {% for i in "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" %}
                                <div class="item" data-value="{{ forloop.counter }}">{{ forloop.counter }}</div>
                              {% endfor %}
                            </div>
                        </div>
                    </div>
                     <div class=" field">
                        <!-- <input placeholder="Year/Month/Day" type="text"> -->
                             <div class="ui fluid search selection dropdown">
                            <input type="hidden" name="a_month" id="achF">
                            <i class="dropdown icon"></i>
                            <div class="default text">Month</div>
                            <div class="menu">
                                {% for i in "xxxxxxxxxxxx" %}
                                <div class="item" data-value="{{ forloop.counter }}">{{ forloop.counter }}</div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                     <div class=" field">
                        <!-- <input placeholder="Year/Month/Day" type="text"> -->
                        <div class="ui fluid search selection dropdown">
                            <input type="hidden" name="a_year" id="achE" required>
                            <i class="dropdown icon"></i>
                            <div class="default text">Select Year</div>
                            <div class="menu">
                                {% for i in year_range %}
                                <div class="item" data-value="{{ i }}">{{ i }}</div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>   

                    <div class=" field">
                        <div class="ui fluid search selection dropdown">
                            <input type="hidden" name="type"  id="achA" required>
                            <i class="dropdown icon"></i>
                            <div class="default text">Achievement Type</div>
                            <div class="menu">
                                <div class="item" data-value="Awards">Awards</div>
                                <div class="item" data-value="Honours">Honours</div>
                                <div class="item" data-value="Prizes">Prizes</div>
                                <div class="item" data-value="Others">Others</div>



                            </div>
                        </div>
                    </div>
                </div>
              


                <div class="fields">
                    <div class="fourteen wide field">
                        <div class="field">
                            <label>Details</label>
                            <input placeholder="Title" type="text"   id="achB" name="details" required>
                        </div>
                    </div>

                    <div class="two wide field">
                        <label><br></label>
                        <button class="ui primary button" type="submit">
                            Save<i class="ui save icon right floated"></i>
                        </button>
                    </div>
                </div>


            </div>
        </form>
        <br>
        <h4 class="ui dividing header">Report:</h4>
        
       <!--scrollbar -->
  <div style="width: 45vw; height: 400px; overflow-y: scroll">   
            
        <table class="ui fixed sortable celled table" id="ach">
            <thead>
            <tr>

                  <th class="sorted ascending" style="width: 7%;">Sr.</th>
                <th class="" style="width: 15%;" >Achievement</th>
                <th class="" style="width: 53%;">Title </th>
                <th class="" style="width: 15%;">Day/Month/Year</th>

                <th style="width:10%">Action</th>
            </tr>
            </thead>

            <tbody>
            {% for award in awards %}
            <tr>
                <td id="ach{{ forloop.counter }}Z"><div style="display: none;">{{ award.id }}</div>{{ forloop.counter }}.</td>
                <td id="ach{{ forloop.counter }}A">{{ award.a_type }}</td>
                <td id="ach{{ forloop.counter }}B">{{ award.details }}</td>
                <td id="ach{{ forloop.counter }}C">{% if award.a_day %}{{ award.a_day }} / {% endif %}{% if award.a_month %}{{ award.a_month }} / {% endif %}{% if award.a_year %}{{ award.a_year }}{% endif %}</td>
                <td><a  class="ui button left floated" onclick="updateACH({{ forloop.counter }})"><i id="bt" class="edit icon" ></i> </a><a class="ui blue button left floated" href="{% url 'eis:achievement_delete' award.id %}"><i id="bt" class="ui red delete icon" ></i></a></td>

            </tr>
            {% endfor %}
            </tbody>


        </table>
    </div>
    </div>

    {% comment %}The Achievements segment ends here!{% endcomment %}



    {% comment %}The Expert Lectures segment starts here!{% endcomment %}
    <div class="{% if mark15 == 1 %}ui active tab segment {% else %} ui tab segment {% endif %}" data-tab="other2">
        <h4 class="ui dividing header"  id="changes13">Add a Expert Lecture/Invited Talks</h4>
           <form class="ui form"  method="post" action="{% url 'eis:talk_insert' %}"  onsubmit="return validateexp()">
                           <div style="display: none;"> <input type="text" id="lecZ" name="lec_id"></div>
            {% csrf_token %}
            <div class="field">
                <div class="three fields">
                <!-- code change starts -->
                    <div class="field">
                        <label>Presentation Type</label>
                        
                          <div class="ui fluid search selection dropdown">
                            <input type="hidden" name="type"  id="lecA" required>
                            <i class="dropdown icon"></i>
                            <div class="default text">Presentation Type</div>
                            <div class="menu">
                                <div class="item" data-value="Invited Talk">Invited Talk</div>
                                <div class="item" data-value="Expert Lecture">Expert Lecture</div>
                              



                            </div>
                        </div>
                    </div>
                    <!-- code change ends -->

                    <div class="field">
                        <label>Place</label>
                        <input placeholder="Place" type="text" name="place" id="lecC" required>
                    </div>
                      <div class="field">
                        <label>Date</label>
                        <!-- <input placeholder="Client" type="text"> -->
                        <!-- code change starts -->
                             <div class="ui calendar" id="example2g">
                                <div class="ui input left icon">
                                  <i class="calendar icon"></i>
                                  <input type="text" placeholder="Date/Time" name="l_date" id="lecD" required>
                                </div>
                              </div>
                          <!-- code change ends -->
                    </div>
                     
                </div>
            </div>

            <div class="field">
                

                <div class="fields">
                    <div class="fourteen wide field">
                        <div class="field">
                            <label>Title</label>
                            <input placeholder="Title" type="text" name="title"  id="lecB" required>
                        </div>
                    </div>

                    <div class="two wide field">
                        <label><br></label>
                        <button class="ui primary button" type="submit">
                            Save<i class="ui save icon right floated"></i>
                        </button>
                    </div>
                </div>

            </div>
        </form>
        <br>
        <h4 class="ui dividing header">Report:</h4>
          <!--scrollbar -->
  <div style="width: 45vw; height: 400px; overflow-y: scroll">
        <table class="ui fixed sortable celled table" id="talk">
            <thead>
            <tr>
              

                <th class="sorted ascending" style="width: 7%;">Sr.</th>
                <th class="" style="width: 15%;" >Presented</th>
                <th class="" style="width: 30%;">Title </th>
                <th class="" style="width: 20%;">Place</th>
                  <th style="width:18%">Date</th>
                <th style="width:10%">Action</th>
            </tr>
            </thead>

            <tbody>

            {% for talk in talks %}
            <tr id="r1">
                <td id="lec{{ forloop.counter }}Z"><div style="display: none;">{{ talk.id }}</div>{{ forloop.counter }}.</td>
                <td id="lec{{ forloop.counter }}A">{{ talk.l_type }}</td>
                <td id="lec{{ forloop.counter }}B">{{ talk.title }}</td>
                <td id="lec{{ forloop.counter }}C">{{ talk.place }}</td>
                <td id="lec{{ forloop.counter }}D">{{ talk.l_date }}</td>
                <td><a class="ui button left floated " onclick="updateLEC({{ forloop.counter }})"><i id="bt" class="edit icon" ></i></a><br><a class="ui blue button left floated" href="{% url 'eis:emp_expert_lecturesDelete' talk.id %}"><i id="bt" class="ui red delete icon" ></i></a></td>

            </tr>
            {% endfor %}
            </tbody>


        </table>
       
    </div>
    </div>

    <!-- {% comment %}The Keynote/Planery Address segment starts here!{% endcomment %}

    <div class="ui tab segment" data-tab="other3">
       eofere

    </div>
    {% comment %}The Technology segment ends here!{% endcomment %} -->
{% endblock %}